export const DEFAULT_IMAGE_GENERATION_HTTP_TIMEOUT_MS = 300_000;
export const MIN_IMAGE_GENERATION_HTTP_TIMEOUT_MS = 30_000;
export const MAX_IMAGE_GENERATION_HTTP_TIMEOUT_MS = 900_000;

export const imageGenerationConfig = {
  httpTimeoutMs: DEFAULT_IMAGE_GENERATION_HTTP_TIMEOUT_MS,
};
